<a href="https://colab.research.google.com/github/SaiSanthosh1508/Brain-Tumour-Image-classification-app/blob/main/PyTorch_ZTM_fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamnetals

In [3]:
import torch
print(torch.__version__)

2.4.1+cu121


## Introduction to tensors

### Creating tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as python int
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
for i in range(len(vector)):
  print(vector[i].item())

7
7


In [15]:
vector.shape

torch.Size([2])

In [16]:
vector.ndim

1

In [17]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [1,2]])
MATRIX

tensor([[7, 8],
        [1, 2]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
MATRIX[0]

tensor([7, 8])

In [23]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]],

                       [[7,8,9],
                       [3,6,2]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [3, 6, 2]]])

In [24]:
TENSOR.shape

torch.Size([2, 2, 3])

In [25]:
TENSOR.ndim

3

In [28]:
TENSOR[1].shape

torch.Size([2, 3])

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with random tensors and adjust those random numbers

In [30]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2422, 0.7594, 0.8026, 0.9661],
        [0.3789, 0.8186, 0.8240, 0.8263],
        [0.0311, 0.5906, 0.7619, 0.7451]])

In [31]:
random_tensor.ndim

2

In [33]:
random_int_tensor = torch.randint(10,20,(4,5))
random_int_tensor

tensor([[18, 19, 18, 16, 15],
        [13, 16, 11, 13, 18],
        [14, 18, 16, 12, 16],
        [17, 13, 17, 14, 14]])

In [34]:
random_int_tensor.ndim

2

In [38]:
# Create a random tensor similar to image tensor
random_image_tensor = torch.rand(size=(3,224,224))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [40]:
random_image_tensor[0].shape

torch.Size([224, 224])

In [41]:
random_image_tensor[0]

tensor([[0.6030, 0.2579, 0.2430,  ..., 0.6503, 0.1689, 0.9653],
        [0.0344, 0.3792, 0.5225,  ..., 0.9187, 0.9710, 0.8505],
        [0.5651, 0.6787, 0.0921,  ..., 0.6260, 0.0550, 0.1563],
        ...,
        [0.2036, 0.1415, 0.8715,  ..., 0.0111, 0.3927, 0.6529],
        [0.9658, 0.7022, 0.9492,  ..., 0.7503, 0.4938, 0.6474],
        [0.3958, 0.2037, 0.0778,  ..., 0.5371, 0.6401, 0.7966]])

### Zeros and Ones

In [42]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4),dtype=torch.int)
ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [47]:
ones.dtype

torch.int32

### Creating a range of tensors and tensor-like

In [53]:
# Use torch.range
one_to_ten = torch.arange(0,10,1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big erros you'll run into with Pytorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [70]:
# Float 32
float_32 = torch.tensor([3.0,6.0,9.0],
                        dtype=torch.float32, # What datatype is the tensor
                        device=None,  # What device is the tensor on
                        requires_grad=False) # Whether or not to track gradients with tensor operations
float_32

tensor([3., 6., 9.])

In [71]:
float_32.dtype

torch.float32

In [72]:
float_16_tensor = float_32.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [75]:
float_16 = float_32
float_16 = float_16.to(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [76]:
float_16 * float_32

tensor([ 9., 36., 81.])

In [77]:
int_32 = torch.tensor([1,2,3],dtype=torch.int32)
int_32

tensor([1, 2, 3], dtype=torch.int32)

In [79]:
int_32 * float_16

tensor([ 3., 12., 27.], dtype=torch.float16)

In [80]:
int_32 * float_32

tensor([ 3., 12., 27.])

In [82]:
long_tensor = torch.tensor([12,3,4],dtype=torch.long)
long_tensor

tensor([12,  3,  4])

### Getting information from Tensors

1. Tensors not right datatype - to get datatype from tensor can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor,can use `tensor.device`

In [84]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6529, 0.0913, 0.9637, 0.8208],
        [0.3805, 0.2486, 0.9864, 0.0092],
        [0.4477, 0.1423, 0.6221, 0.5368]])

In [87]:
print(some_tensor)
print(f"\nData type of tensor: {some_tensor.dtype}")
print(f"\nShape of the tensor: {some_tensor.shape}")
print(f"\nSize of the tensor: {some_tensor.size()}")
print(f"\nDevice of the tensor: {some_tensor.device}")

tensor([[0.6529, 0.0913, 0.9637, 0.8208],
        [0.3805, 0.2486, 0.9864, 0.0092],
        [0.4477, 0.1423, 0.6221, 0.5368]])

Data type of tensor: torch.float32

Shape of the tensor: torch.Size([3, 4])

Size of the tensor: torch.Size([3, 4])

Device of the tensor: cpu


> **Note:** By default the tensor are on `CPU`

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [88]:
# Create a tensor and add 10 to it
tensor  = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [89]:
# Multipy the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [90]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [91]:
# Try out PyTorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [92]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [94]:
torch.subtract(tensor,5)

tensor([-4, -3, -2])

### Matrix Multiplication

There are two main ways of performing multiplication in neural networks and deep learning

* Element-Wise Multiplication
* Matrix Multiplication(dot product)

There are two rules that performing matrix multiplciation should satisfy:

1. The **inner dimension** must match:
* `(3,2) @ (3,2) ` won't work
* `(2,3) @ (3,2 )` will work

2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (3,2) -> (2,2)`

In [95]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [97]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [98]:
tensor.shape

torch.Size([3])

In [101]:
k = torch.matmul(torch.rand(3,2),torch.rand(2,3))
k.shape

torch.Size([3, 3])

In [102]:
k

tensor([[0.1371, 0.1184, 0.1485],
        [0.4457, 0.5057, 0.5448],
        [0.4626, 0.6951, 0.6530]])

### One of the most common errors in deep learning: shape errors

In [103]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm is the same as torch.matmul its an alias
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [104]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

> To fix our tensor shape issues,we can manipulate the shape of our tensors using the `transpose`

In [107]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [106]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

### Finding the min,max,mean,sum,etc (Tensor Aggregation)

In [108]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [111]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [112]:
# Find the max
torch.max(x),max(x)

(tensor(90), tensor(90))

In [119]:
# Find the mean
torch.mean(x.type(torch.float32)),x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

> **Note:**  `torch.mean()` requires a tensor of float datatype to work

### Finding the positional max and min

In [120]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [121]:
# Find the postion of element that is the maximum value in the tensor
torch.argmax(x)

tensor(9)

In [122]:
# Find the position of element that is the minimum value in the tensor
torch.argmin(x)

tensor(0)

### Reshaping,stacking ,squeezing and unsqueezing

* `Reshaping` - reshapes an input tensor to the defined shape
* `View` - Return a view of the input tensor of certain shape but keep the same memory
* `Stacking` - combine multiple tensors on top of each other (vstack or hstack)
* `Squeeze` -  removes all `1` dimension from a tensor
* `Unsqueeze` - add a `1` dimension to target tensot
* `Permute` - Return a view of the input with dimensions permuted(swapped) in a certain way

In [132]:
# Let's create a tensor
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [133]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [134]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

> **Note:** In the above changing z changes x as it is referred by the location of x

In [135]:
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [137]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [140]:
# Squeezing the tensors
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [141]:
x_reshaped.shape

torch.Size([1, 9])

In [144]:
x_reshaped = x_reshaped.squeeze()

In [145]:
x_reshaped.shape

torch.Size([9])

In [146]:
# Unsqueeze the tensors
x_reshaped = torch.unsqueeze(x_reshaped,dim=0)
x_reshaped,x_reshaped.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [147]:
# torch.permute - rearranges the dimensions of target tensor in specified order
x_original = torch.rand((224,224,3))

# permute the original tensor to re arrange the axis(or dim) order
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing (selecting data from tensors)

In [148]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [149]:
# Let's index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [150]:
# Let's idnex on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [151]:
# Lets index ont the last bracket
x[0][0][0]

tensor(1)

In [152]:
# You can also use the ":" to select all of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [153]:
x[:,:,0]

tensor([[1, 4, 7]])

In [154]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### PyTorch tensors and numpy

* Data in Numpy,want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch Tensoor -> Numpy -> `torch.Tensor.numpy()`

In [157]:
import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [158]:
array.dtype,tensor.dtype

(dtype('int64'), torch.int64)

In [159]:
# Change the value of array,what will this do to `tensor`?
array = array + 1
array,tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [160]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [164]:
torch.rand(3,3)

tensor([[0.2580, 0.3193, 0.5463],
        [0.6241, 0.5934, 0.0536],
        [0.7718, 0.6641, 0.8888]])

In [170]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4557, 0.3461, 0.9724, 0.1135],
        [0.5120, 0.7093, 0.6968, 0.1021],
        [0.3003, 0.6102, 0.8789, 0.0911]])
tensor([[0.4509, 0.4945, 0.1518, 0.3916],
        [0.5022, 0.8075, 0.5362, 0.2507],
        [0.9362, 0.0867, 0.4542, 0.0783]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [173]:
# Let's make some random but reproducible tensors
import torch

torch.manual_seed(42)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(42)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


>**Note:** It only works for one block of code i.e one random function

### Running tensors and PyTorch objects on GPU

In [174]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-7e2a2f4a-77c1-45dc-4ec2-002457525f09)


### Check for GPU access with PyTorch

In [175]:
import torch
torch.cuda.is_available()

True

> **Note:** For PyTorch since it's capable of running compute on the GPU or CPU,it's best practice to setup device agnostic code

In [177]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [178]:
# Count the number of devices
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [181]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [182]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [183]:
# If tensor is on gpu ,can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [184]:
# To fix the gpu tensor with numpy issue,we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])